set(_CATKIN_CURRENT_PACKAGE "prometheus_mission")
set(prometheus_mission_VERSION "0.0.0")
set(prometheus_mission_MAINTAINER "Yuhua Qi <fatmoonqyp@126.com>")
set(prometheus_mission_PACKAGE_FORMAT "2")
set(prometheus_mission_BUILD_DEPENDS "message_generation" "std_msgs")
set(prometheus_mission_BUILD_EXPORT_DEPENDS "std_msgs")
set(prometheus_mission_BUILDTOOL_DEPENDS "catkin")
set(prometheus_mission_BUILDTOOL_EXPORT_DEPENDS )
set(prometheus_mission_EXEC_DEPENDS "message_runtime" "std_msgs")
set(prometheus_mission_RUN_DEPENDS "message_runtime" "std_msgs")
set(prometheus_mission_TEST_DEPENDS )
set(prometheus_mission_DOC_DEPENDS )
set(prometheus_mission_URL_WEBSITE "http://www.amovauto.com/")
set(prometheus_mission_URL_BUGTRACKER "")
set(prometheus_mission_URL_REPOSITORY "https://github.com/amov-lab/Prometheus.git")
set(prometheus_mission_DEPRECATED "")